[package]
name = "migrations"
version = "0.0.0"
edition = "2021"
description = "The migrations for the database of todoist tracker"

[dependencies]
tokio.workspace = true
clap.workspace = true
rusqlite.workspace = true
directories.workspace = true
reqwest.workspace = true

[[bin]]
path = "src/main.rs"
name = "todoist-tracker-migrations"